name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run Flutter analyzer
      - name: Analyze code
        run: flutter analyze

      # Run Flutter tests
      - name: Run tests
        run: flutter test

      # Build the app (optional, for release builds)
      - name: Build APK
        run: flutter build apk --release