name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: stable

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run Flutter tests
      #- name: Run tests
      #  run: flutter test

      # Build the app (optional, for release builds)
      - name: Build Flutter web app
        run: flutter build web
